const {version, versions} = require('node:process');
const fs = require("node:fs")
const path = require("node:path")

let data = `// Code generated by process/index.js; DO NOT EDIT.
package process

// Version of the NodeJS SDK
const Version = "${process.version}"

// Versions as returned by the NodeJS SDK
var Versions = map[string]any{`

for (let [key, value] of Object.entries(versions)) {
    data += `\n  "${key}": "${value}",`
}

data += `
}
`

fs.writeFileSync(path.resolve(__dirname, "./module.gen.go"), data)
